spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost:8889}/${DB_NAME}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    generate-ddl: true
    show-sql: true

server:
  port: {$PORT:8080}